version: '3'

services:
  vilzyDB:
    image: postgis/postgis:15-3.3
    container_name: vilzy_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vilzy
      - POSTGRES_PASSWORD=vilzy2026
      - POSTGRES_DB=vilzy_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - vilzy_network

  #Redis para BullMQ (Colas y cache)
  vilzy_redis:
    image: redis:7.2-alpine
    container_name: vilzy_redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - vilzy_network

networks:
  vilzy_network:
    driver: bridge
