version: '3'

services:
  vilzyDB:
    image: postgis/postgis:15-3.3
    container_name: vilzy_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vilzy
      - POSTGRES_PASSWORD=vilzy2026
      - POSTGRES_DB=vilzy_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
